version: '3.8'
services:
  h2:
    container_name: h2
    image: 'oscarfonts/h2:latest'
    volumes:
      - ./h2/:/opt/h2-data
    ports:
      - '1520:1521'
    env_file:
      - ./env/h2.env
    networks:
      - test_network_02
  backend:
    build:
      context: ./build/libs/
      dockerfile: LazyAddress.Dockerfile
    container_name: lazyaddress_backend
    ports:
      - '8081:8080'
    volumes:
      - ./build/libs/:/app
    env_file:
      - ./env/backend.env
    depends_on:
      - h2
    networks:
      - test_network_02

networks:
  test_network_02:
