spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/lazyaddress
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
<<<<<<< HEAD
        #show_sql: true
=======
        show_sql: true
>>>>>>> 9f9c14b1ec95c63003ef0a621055ed2266f826dc
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect


logging.level:
  org.hibernate.SQL: debug